export const songs = [
  "The Return of Chip Douglas",
  "Anomaly",
  "The Nothing",
  "MELTING",
  "Beautiful Trip",
  "Edge of the Earth",
  "MANIAC",
  "We Aite",
  "The Mood",
  "Trauma",
  "Embers",
  "Is There Any Love",
  "New York City Rage Fest",
  "In My Dreams 2015",
  "Cudi Get",
  "Save My Soul",
  "CuDi Spazzin’",
  "Destination: Mother Moon",
  "The Flight of the Moon Man",
  "Entergalactic Theme",
  "Worth",
  "Afterwards",
  "WAIT!",
  "The Resurrection of Scott Mescudi",
  "Going to the Ceremony",
  "Young Lady",
  "Whenever",
  "Pillow Talk",
  "Girls",
  "Red Sabbath",
  "Adventures",
  "Red Eye",
  "Ignite The Love",
  "Troubled Boy",
  "Hyyer",
  "Scott Mescudi vs. The World",
  "Simple As",
  "Burrow",
  "Brothers",
  "Releaser",
  "Maybe So",
  "AMEN",
  "Seance Chaos",
  "Angered Kids",
  "Lord I Know",
  "Angel",
  "My Drug",
  "All In",
  "Man In The Night",
  "Internal Bleeding",
  "Solo Dolo Pt.II",
  "Wild’n Cuz I’m Young",
  "Maui Wowie",
  "Elsie’s Baby Boy",
  "Copernicus Landing",
  "Somewhere To Fly",
  "The End",
  "Trapped In My Mind",
  "Does It",
  "Cosmic Warrior",
  "Fade 2 Red",
  "Speedin Bullet 2 Heaven Acoustic",
  "Speedin Bullet 2 Heaven",
  "Return of the Moon Man",
  "Mad Solar",
  "King Wizard",
  "Beez",
  "Fuschia Butterflies",
  "Cold Blooded",
  "Burn Baby Burn",
  "Wedding Tux",
  "Fairytale Remains",
  "Screwed",
  "Unfuckwittable",
  "Down & Out",
  "Can’t Believe It",
  "4 Da Kidz",
  "Satellite Flight",
  "Make Her Say",
  "Can’t Shake Her",
  "Livin My Truth",
  "My World",
  "Don’t Play This Song",
  "Ashin Kusher",
  "These Worries",
  "Heart of a Lion",
  "Heaven at Nite",
  "Embrace The Martian",
  "The Prayer",
  "Willing To Trust",
  "She’s Looking For Me",
  "REVOFEV",
  "Dive",
  "Lovin Me",
  "Sept. 16",
  "The Commander",
  "Flight at First Sight",
  "Dance 4 Eternity",
  "The Pale Moonlight",
  "Lord of the Sad And Lonely",
  "New Mode",
  "In Love",
  "Do What I Want",
  "CONFUSED!",
  "Rose Golden",
  "Show Out",
  "Another Day",
  "Up Up & Away",
  "Enter Galactic",
  "T.G.I.F",
  "Cudi Zone",
  "Sky Might Fall",
  "ILLusions",
  "Man On The Moon",
  "Solo Dolo",
  "In My Dreams",
  "Damaged",
  "Swim In The Light",
  "Insides Out",
  "Judgmental Cunt",
  "Frequency",
  "Wounds",
  "Handle With Care",
  "Damaged",
  "Kitchen",
  "Mojo So Dope",
  "Sad People",
  "Balmain Jeans",
  "Tequila Shots",
  "The Guide",
  "Mature Nature",
  "Surfin",
  "Rockstar Knights",
  "Cleveland Is The Reason",
  "Soundtrack 2 My Life",
  "Too Bad I Have To Destroy You Now",
  "Immortal",
  "All Along",
  "Marijuana",
  "Erase Me",
  "Ghost!",
  "By Design",
  "Baptized in Fire",
  "Distant Fantasies",
  "Just What I Am",
  "She Knows This",
  "Heaven On Earth",
  "Alive",
  "The Void",
  "Mr.Rager",
  "Pursuit of Happiness",
  "Solo Dolo Pt.III",
] as const;
